# Generated by Django 3.0 on 2020-02-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('designation', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=10)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
