# Generated by Django 3.0 on 2020-02-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewid', models.IntegerField()),
                ('interviewer', models.IntegerField()),
                ('schedule', models.DateField()),
                ('applicantid', models.IntegerField()),
                ('result', models.CharField(max_length=30)),
            ],
        ),
    ]
