# Generated by Django 2.2.12 on 2020-04-19 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interviewer', '0002_auto_20200419_1446'),
        ('Manager', '0002_auto_20200419_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinterviewmodel',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Manager.NewInterViewSchModel'),
        ),
    ]
