# Generated by Django 2.2.12 on 2020-04-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interviewer', '0003_newinterviewmodel_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinterviewmodel',
            name='applicationid',
            field=models.IntegerField(),
        ),
    ]
