# Generated by Django 2.2.12 on 2020-04-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='address',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='address',
            field=models.CharField(max_length=30),
        ),
    ]
