# Generated by Django 3.0 on 2020-02-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewRecruitModel',
            fields=[
                ('opcode', models.IntegerField(primary_key=True, serialize=False)),
                ('quali', models.CharField(max_length=30)),
                ('regstart', models.DateField()),
                ('agelim', models.IntegerField()),
                ('lastdate', models.DateField()),
                ('deptid', models.CharField(max_length=10)),
                ('nofposn', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
                ('resp', models.CharField(max_length=250)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
